In [1]:
import numpy as np
import math

In [2]:
arrlist = np.array([[.10,20.6,30,],
                    [40,50,60.1,],
                    [70,80,90]])
arrlist

array([[ 0.1, 20.6, 30. ],
       [40. , 50. , 60.1],
       [70. , 80. , 90. ]])

In [3]:
arrlist[:2,:3][1][2]

60.1

In [4]:
arrlist[2]

array([70., 80., 90.])

# if we want to change element of array

In [5]:
arrlist[1,1] = 51

In [6]:
arrlist

array([[ 0.1, 20.6, 30. ],
       [40. , 51. , 60.1],
       [70. , 80. , 90. ]])

In [7]:
arrlist.shape

(3, 3)

In [8]:
arrlist.size

9

In [9]:
arrlist.data

In [10]:
arrlist.ndim

2

In [11]:
arrlist.itemsize

8

In [12]:
arrlist.dtype  

dtype('float64')

# HERE USING FUCTION LIKE, ARRANGE, ONE, ZERO, LINSPACE, REVEL, EMPTY_LIKE, RESHAPE,   IDENTITY, 

In [13]:
arr = np.arange(20) # arange method is same like a range method 

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
arr.reshape(2,10) # reshape have property to reshape the array but it must have same r*c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [16]:
arr2 = np.zeros((2, 6)) # this zero method is use to create an array of value having zero with float  

In [17]:
arr2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
arr3 = np.ones((10, 5)) # this one function can create an array which having one value with float value

In [19]:
arr3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
lins = np.linspace(1,10,20) # linspace funtion is use to create an array with start, destination, and how many elment

In [21]:
lins

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [22]:
empt = np.empty((3,3)) # this function is use to create an array with the random value 

In [23]:
empt

array([[ 0.1, 20.6, 30. ],
       [40. , 51. , 60.1],
       [70. , 80. , 90. ]])

In [24]:
emt_lik = np.empty_like(lins) # this empty_like function is use to create an array of copy 

In [25]:
emt_lik

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [26]:
ide = np.identity((50)) # this will make an array of identity array

In [27]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

# MATHMETHICAL OPERATIONS

In [28]:
arn = np.around(arrlist) # the around function is use to create the an array if there is any point value it can round give the decimal value

In [29]:
arn

array([[ 0., 21., 30.],
       [40., 51., 60.],
       [70., 80., 90.]])

In [30]:
expn = np.exp(arn) # this will find the exponation value of array(like find the log of all value)

In [31]:
expn

array([[1.00000000e+00, 1.31881573e+09, 1.06864746e+13],
       [2.35385267e+17, 1.40934908e+22, 1.14200739e+26],
       [2.51543867e+30, 5.54062238e+34, 1.22040329e+39]])

In [32]:
logg = np.log(expn) # it is an inverse of the exponantion

In [33]:
logg

array([[ 0., 21., 30.],
       [40., 51., 60.],
       [70., 80., 90.]])

In [34]:
arr2 = np.array([[2.0,3.0,8.0]])

In [35]:
arr2

array([[2., 3., 8.]])

In [36]:
recip = np.reciprocal(arr2) # in the reciprolcal functotion is to 1/n.

In [37]:
recip

array([[0.5       , 0.33333333, 0.125     ]])

In [38]:
# use this link for refer the mathmatic operation in numpy
#https://www.geeksforgeeks.org/numpy-mathematical-function/

In [39]:
arn

array([[ 0., 21., 30.],
       [40., 51., 60.],
       [70., 80., 90.]])

** add, mult, div, reminder,**

In [40]:
add_array = np.sum(arn) # the sum function return the all array sum
add_array

442.0

In [41]:
arrnn = np.array([[1,2,3],
                 [4,5,6]])

In [42]:
arn2 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arn2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
add_arr = arn + arn2
add_arr

array([[ 1., 23., 33.],
       [44., 56., 66.],
       [77., 88., 99.]])

In [44]:
#small_big_arr = arn2 + arrnn # GETTING ERROR BRO

In [45]:
mult_arr = np.multiply(arr2, arrnn)

In [46]:
np.sqrt(add_arr)

array([[1.        , 4.79583152, 5.74456265],
       [6.63324958, 7.48331477, 8.1240384 ],
       [8.77496439, 9.38083152, 9.94987437]])

In [47]:
arn2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arrnn

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
mult_arr

array([[ 2.,  6., 24.],
       [ 8., 15., 48.]])

**  axis = 0, 1**

In [50]:
axi_arr = np.array([[4,5,2],
                   [8,7,6],
                   [7,8,3]]
                  )
axi_arr

array([[4, 5, 2],
       [8, 7, 6],
       [7, 8, 3]])

In [51]:
axi_arr.sum(axis = 1) # see this is way where we can use axis for an array

array([11, 21, 18])

In [52]:
axi_arr.sum(axis = 0)

array([19, 20, 11])

In [53]:
axi_arr.ndim

2

In [54]:
axi_arr.data

In [55]:
axi_arr.flat

In [56]:
for i in axi_arr.flat:  # flat is iterator it is use to iterate the array
    print(i)

4
5
2
8
7
6
7
8
3


In [57]:
axi_arr.size

9

In [58]:
axi_arr.shape

(3, 3)

In [59]:
axi_arr.nbytes # that will print how many memory consume 

36

In [60]:
single_arr = np.array([[1,2,3,4545,7,87]])
single_arr

array([[   1,    2,    3, 4545,    7,   87]])

In [61]:
np.argmax(single_arr) # this will be print the big element in your array by the position

3

In [62]:
single_arr.argmax() #  this will be print the big element in your array by the position(index)

3

In [63]:
single_arr.argmin()

0

In [64]:
single_arr.argsort()  # argsort method is print sort the array with the array element position(index)

array([[0, 1, 2, 4, 5, 3]], dtype=int64)

In [65]:
axi_arr

array([[4, 5, 2],
       [8, 7, 6],
       [7, 8, 3]])

In [66]:
axi_arr.argmax(axis = 0) # it working with the index of array element (index)

array([1, 2, 1], dtype=int64)

In [67]:
axi_arr.argmax(axis = 1)

array([1, 0, 1], dtype=int64)

In [68]:
axi_arr.argmin(axis = 0)

array([0, 0, 0], dtype=int64)

In [69]:
axi_arr.argmin(axis = 1)

array([2, 2, 2], dtype=int64)

In [70]:
axi_arr.argsort(axis = 0) # this all are working on the axis 

array([[0, 0, 0],
       [2, 1, 2],
       [1, 2, 1]], dtype=int64)

In [71]:
axi_arr.argsort(axis = 1)

array([[2, 0, 1],
       [2, 1, 0],
       [2, 0, 1]], dtype=int64)

In [72]:
axi_arr.ravel() # this will make array in a straight or single dimension 

array([4, 5, 2, 8, 7, 6, 7, 8, 3])

In [73]:
axi_arr

array([[4, 5, 2],
       [8, 7, 6],
       [7, 8, 3]])

In [74]:
#arn2 * arrnn # here also we are getting valueeror

In [75]:
np.min(axi_arr)

2

In [76]:
axi_arr.min()

2

In [77]:
np.max(axi_arr)

8

In [78]:
axi_arr.argsort(axis = 1) 

array([[2, 0, 1],
       [2, 1, 0],
       [2, 0, 1]], dtype=int64)

In [79]:
axi_arr

array([[4, 5, 2],
       [8, 7, 6],
       [7, 8, 3]])

In [80]:
# if want to condition in array of numpy then we are using where and many function are there so on.......
np.where(axi_arr>5)

(array([1, 1, 1, 2, 2], dtype=int64), array([0, 1, 2, 0, 1], dtype=int64))

In [81]:
np.count_nonzero(axi_arr) # this method will count all the nonzero element

9

In [82]:
np.nonzero(axi_arr) # this method write the nonzero position in row*column

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

# TO BE FIND MEMORY SPACE COMPARE TO THE LIST

In [83]:
import sys

In [84]:
py_arr = [1,2,3,4,5,6,7,8,9]

In [85]:
np_arr12 = np.array(py_arr)

In [86]:
sys.getsizeof(1) * len(py_arr)

252

In [87]:
np_arr12.itemsize * np_arr12.size

36

** now you can see that what's the difference between the py_arr of list and numpy array **

In [88]:
axi_arr

array([[4, 5, 2],
       [8, 7, 6],
       [7, 8, 3]])

In [89]:
axi_arr.dim()

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

# we can also create an array 

In [90]:

np.ndarray(shape=(2,2), dtype=float, order='F')


array([[1.01631507e-311, 1.16466228e-028],
       [9.08367237e+223, 1.01634057e-311]])

In [91]:
axi_arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [92]:
axi_arr

array([[4, 5, 2],
       [8, 7, 6],
       [7, 8, 3]])

In [93]:
arn2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
axi_arr.dot(arn2)

array([[ 38,  49,  60],
       [ 78,  99, 120],
       [ 60,  78,  96]])

# IF WE WANT TO DEFINE OWN DATA TYPES 

In [95]:
dtypes = [('name','S10'), ('year',int), ('date', int)]

In [96]:
valu = [('python', 1991,20021991), ('bala', 1997, 31101997), ('tejash', 1997, 2081997)]

In [97]:
arr5 = np.array(valu, dtype = dtypes)

In [98]:
arr5

array([(b'python', 1991, 20021991), (b'bala', 1997, 31101997),
       (b'tejash', 1997,  2081997)],
      dtype=[('name', 'S10'), ('year', '<i4'), ('date', '<i4')])

In [99]:
np.sort(arr5, order='name')

array([(b'bala', 1997, 31101997), (b'python', 1991, 20021991),
       (b'tejash', 1997,  2081997)],
      dtype=[('name', 'S10'), ('year', '<i4'), ('date', '<i4')])

In [100]:
np.sort(arr5, order='date')

array([(b'tejash', 1997,  2081997), (b'python', 1991, 20021991),
       (b'bala', 1997, 31101997)],
      dtype=[('name', 'S10'), ('year', '<i4'), ('date', '<i4')])

In [101]:
axi_arr

array([[4, 5, 2],
       [8, 7, 6],
       [7, 8, 3]])

In [102]:
dim(axi_arr)

NameError: name 'dim' is not defined

In [107]:
np.prod(axi_arr)

2257920

In [108]:
np.sum(axi_arr)

50

In [112]:
np.percentile(axi_arr, 0.9)

2.072

In [118]:
np.any(axi_arr, 1)

array([ True,  True,  True])

In [116]:
axi_arr

array([[4, 5, 2],
       [8, 7, 6],
       [7, 8, 3]])

In [122]:
np.all(axi_arr, 1)

array([ True,  True,  True])

In [123]:
np.std(axi_arr)

2.0608041101101566

In [124]:
np.var(axi_arr)

4.246913580246914

In [126]:
axi_arr[1,1] = 0

In [127]:
axi_arr

array([[4, 5, 2],
       [8, 0, 6],
       [7, 8, 3]])

In [128]:
np.nansum(axi_arr)

43

In [131]:
np.argmin(axi_arr)

4

In [140]:
rando_arr = [np.random.random((3,3)).reshape(1,9)]

In [141]:
rando_arr

[array([[0.74664279, 0.84524849, 0.1160822 , 0.90081429, 0.88225253,
         0.68798697, 0.43922204, 0.18349961, 0.76547388]])]