In [1]:
import numpy as np

In [2]:
a = np.array([[0, np.pi/2, np.pi]])

In [3]:
a

array([[0.        , 1.57079633, 3.14159265]])

In [4]:
np.sin(a)

array([[0.0000000e+00, 1.0000000e+00, 1.2246468e-16]])

In [5]:
b = np.array([[1,2,3]
             ,[4,5,6]])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.exp(b)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [8]:
np.fabs(b)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [9]:
np.round(b)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.cos(b)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [11]:
np.log(b)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [12]:
np.reciprocal(b)

array([[1, 0, 0],
       [0, 0, 0]], dtype=int32)

In [13]:
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [14]:
c = np.array([[7,5,8],
             [4,7,1]])

In [15]:
np.sort(c, axis= None)

array([1, 4, 5, 7, 7, 8])

In [16]:
np.sort(c, axis= 0, kind = 'mergesort')

array([[4, 5, 1],
       [7, 7, 8]])

In [17]:
np.sort(c, axis= 0)

array([[4, 5, 1],
       [7, 7, 8]])

In [20]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
b.diagonal()

array([1, 5])

In [39]:
x = np.eye(3)

In [40]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
 x.setfield(3, np.int32)

In [53]:

x

array([[1.5e-323, 1.5e-323, 1.5e-323],
       [1.5e-323, 1.5e-323, 1.5e-323],
       [1.5e-323, 1.5e-323, 1.5e-323]])